apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: auto-goqeerogxq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: auto-goqeerogxq 
  name: auto-goqeerogxq
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: auto-goqeerogxq
    weight: 100 
