apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: auto-goqeerogxq
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/quay_xjiang/auto-goqeerogxq:852d6ac279cec4fd90dc89a5e095f449e3660976@sha256:56dffa53a7405af05e68ebdc7b20404925b8a3dd4af5dbb2980f0c6a85738149
          name: container-image
